apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.pod.label }}